name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v**

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    uses: tryAGI/workflows/.github/workflows/dotnet-sdk-build-test-publish.yml@main
    with:
      project-path: GoogleCloudSpeech.slnx
      enable-caching: false
      publish: true
      auto-stable-release: true
      run-tests: true
      additional-test-arguments: '--logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
